DEFAULT_TOLERANCE = 5.0
DEFAULT_SLOPE_CHANGE = 0.03
DEFAULT_MAX_DISTANCE = 100.0
DEFAULT_PEAK_PROMINENCE = 0.30

SUPPORTED_EXCEL_EXTENSIONS = (".xls", ".xlsx")
SUPPORTED_EXTENSIONS = SUPPORTED_EXCEL_EXTENSIONS + (".pdf",)

SAVE_MODE_COMPAT_24 = "2.4 호환 저장"
SAVE_MODE_EXTENDED_31 = "3.1 확장 저장"
SAVE_MODE_COMPAT_33 = "3.3 호환 저장"
SAVE_MODES = (SAVE_MODE_COMPAT_24, SAVE_MODE_EXTENDED_31, SAVE_MODE_COMPAT_33)
